agnesoft/agdb

src/storage/file_records.rs
=> [storage] Add get_mut() to FileRecords #114

.github/workflows/pr.yaml, src/storage/file_records.rs
=> [storage] Use Vec in FileRecords #126

.github/workflows/pr.yaml, src/storage.rs, src/storage/file_storage.rs
=> [storage] Add resize_value() to Storage #156

src/storage/storage_vec.rs
=> [storage] Add indexed access to StorageVec #165

src/storage.rs, src/storage/file_storage.rs, src/storage/serialize.rs, src/storage/storage_impl.rs
=> [storage] Add insertion of slices to Storage #184

.github/workflows/pr.yaml, src/graph.rs, src/graph/graph_node.rs, src/graph/graph_node_iterator.rs
=> [graph] Add node iteration #240

crates/dictionary/src/dictionary_data.rs, crates/dictionary/src/dictionary_data_memory.rs, crates/dictionary/src/dictionary_data_memory_default.rs, crates/dictionary/src/dictionary_data_storage.rs, crates/dictionary/src/dictionary_data_storage_indexes.rs, crates/dictionary/src/dictionary_impl.rs, crates/dictionary/src/dictionary_index.rs, crates/dictionary/src/dictionary_index_from.rs, crates/dictionary/src/dictionary_index_serialize.rs, crates/dictionary/src/lib.rs, crates/dictionary/src/storage_dictionary_try_from.rs, crates/dictionary/tests/dictionary_get_index_test.rs, crates/dictionary/tests/dictionary_index_test.rs, crates/dictionary/tests/dictionary_insert_test.rs, crates/dictionary/tests/dictionary_remove_test.rs, crates/dictionary/tests/dictionary_test.rs, crates/dictionary/tests/storage_dictionary_get_index_test.rs, crates/dictionary/tests/storage_dictionary_insert_test.rs, crates/dictionary/tests/storage_dictionary_remove_test.rs, crates/dictionary/tests/storage_dictionary_test.rs, crates/storage_index/src/storage_index_from.rs
=> [storage] Add DictionaryIndex #303

crates/graph_search/src/breadth_first_search.rs, crates/graph_search/src/depth_first_search.rs, crates/graph_search/src/graph_search.rs, crates/graph_search/src/graph_search_from.rs, crates/graph_search/src/lib.rs, crates/graph_search/src/search_impl.rs, crates/graph_search/src/search_index.rs, crates/graph_search/src/search_iterator.rs, crates/graph_search/tests/breadth_first_search_test.rs, crates/graph_search/tests/depth_first_search_test.rs
=> [graph] Add DepthFirstSearch to GraphSearch #323

crates/commands/Cargo.toml, crates/commands/src/command.rs, crates/commands/src/command_executor.rs, crates/commands/src/command_stack.rs, crates/commands/src/lib.rs, crates/commands/tests/command_stack.rs, crates/commands/tests/commands_test.rs
=> [commands] Add CommandStack #331

src/agdb/collections/vec_storage.rs
=> [collections] Add swap() to VecStorage #378

src/agdb/query_builder.rs, src/agdb/query_builder/select.rs, src/agdb/query_builder/select_key_count.rs, src/agdb/query_builder/select_key_count_from.rs, tests/select_key_count_test.rs
=> [query] Add select key count #425

src/agdb/commands_mut.rs, src/agdb/commands_mut/insert_alias.rs, src/agdb/query/insert_aliases_query.rs, src/agdb/query/query_id.rs, src/agdb/transaction_mut.rs, tests/insert_aliases_test.rs
=> [db] Simplify insert alias #493

src/agdb/collections/multi_map.rs, src/agdb/db.rs, src/agdb/query/select_key_count_query.rs, tests/select_key_count_test.rs
=> [query] Implement select key count #556

src/agdb/db.rs, src/agdb/db/db_search_handlers.rs, src/agdb/graph_search.rs, src/agdb/graph_search/breadth_first_search.rs, src/agdb/graph_search/breadth_first_search_reverse.rs, src/agdb/graph_search/depth_first_search.rs, src/agdb/graph_search/depth_first_search_reverse.rs, src/agdb/graph_search/path_search.rs, src/agdb/graph_search/search_impl.rs
=> [graph] Allow search to return result #584

docs/queries.md, src/agdb/query_builder/insert_aliases.rs, tests/insert_aliases_test.rs
=> [query] Use ids instead of of for aliases #610

docs/guide.md, docs/queries.md, src/agdb/db.rs, src/agdb/query/query_condition.rs, src/agdb/query_builder/search.rs, src/agdb/query_builder/where_.rs, tests/examples.rs
=> [docs] Add in-depth guide #611

agdb/src/storage/file_storage.rs, agdb/src/storage/write_ahead_log.rs, agdb/src/test_utilities/test_file.rs
If the WAL (write ahead lof, the dot file) became corrupted it would not be loadable and in effect the db would not load. The workaround would be to remove the faulty WAL file. This could however leave the db in an invalid state as some data might have been only partially written. Furthermore if there was a transaction in progress it would not get correctly reverted.
This change adds the "repair" routine to the WAL which validates it upon load and truncates it at first invalid record it encounters. This should cover all possible cases as if the WAL write did not complete for any reason the main db write never happened to begin with. The remaining records in the WAL then should still correctly revert and undo any transactions or writes that have been in progress.
=> [db] Repair wal if it is incomplete #1060

agdb_api/rust/src/api.rs, agdb_api/typescript/src/client.ts, agdb_api/typescript/tests/OpenApi.test.ts, agdb_server/Cargo.toml, agdb_server/src/app.rs, agdb_server/src/config.rs, agdb_server/tests/routes/cluster_test.rs, agdb_server/tests/routes/misc_routes.rs, agdb_server/tests/test_server.rs, docs/server.md, examples/server_client_typescript/main.ts
Allow setting different basepath. And support for static web services.
=> [server] Allow setting different basepath and static web #1104

agdb_web/pages/docs/references/queries.en-US.md
Removal of one character for a typo fix.
=> [docs] Small typo fix in queries.en-US.md #0

agdb_server/src/routes/user.rs, agdb_server/src/server_db.rs, agdb_server/tests/routes/user_login_test.rs
Added `save_or_get_token` to return existing token if present, ensuring concurrent logins for the same user receive the same token. Updated login route to use this method and added a test to verify token consistency across concurrent logins.
=> [tests] Fix rarely occuring 401 in agdb_server integration tests #1630

.github/workflows/agdb.yaml, .github/workflows/agdb_benchmarks.yaml, .github/workflows/agdb_server.yaml, .github/workflows/examples.yaml, agdb/src/db/db_value.rs
…Value
Implemented From and TryFrom traits to allow conversion between DbValue and PathBuf, SystemTime, SocketAddr, and IpAddr. Added corresponding tests to ensure correct serialization and deserialization, including error handling for invalid conversions.
=> [db] Implement TryFrom<DbValue> for standard library types #1651
