agnesoft/agdb

.github/pull_request_template.md

[ci] Add PR template #3

---

.github/workflows/pr.yaml

[ci] Add pull request build #5

---

.github/workflows/pr_title.yaml

[ci] Add PR title check #7

---

.github/workflows/pr.yaml

[ci] Limit PR build to Rust code changes #9

---

.github/workflows/pr.yaml

[ci] Add Rust code analysis #11

---

.github/workflows/pr.yaml

[ci] Add code coverage as PR check #13

---

.github/workflows/pr.yaml

[ci] Fix unmergable PRs with non-code changes #17

---

.github/workflows/coverage.yaml
.github/workflows/pr_title.yaml

[ci] Add codecov on main #15

---

.github/workflows/coverage.yaml

[ci] Fix codecov upload #19

---

.github/workflows/build.yaml

[ci] Add release dry run #21

---

.github/workflows/build.yaml
.github/workflows/coverage.yaml
README.md

[ci] Add badges to readme #23

---

.github/workflows/pr_title.yaml

[ci] Add component db to components #27

---

src/db.rs
src/lib.rs
tests/db_test.rs

[db] Add Db struct #25

---

src/lib.rs
src/query.rs
tests/query_test.rs

[query] Add Query struct #29

---

src/lib.rs
src/query_result.rs
tests/query_result_test.rs

[query] Add QueryResult struct #31

---

src/db.rs
tests/db_test.rs

[db] Add Db::exec() function #33

---

src/lib.rs
src/transaction.rs
tests/transaction_test.rs

[query] Add Transaction #35

---

src/db.rs
tests/transaction_test.rs

[db] Create Transaction from Db #37

---

src/transaction.rs
tests/transaction_test.rs

[query] Add exec() to Transaction #39

---

src/transaction.rs
tests/transaction_test.rs

[query] Add nested transactions #41

---

src/lib.rs
src/query_error.rs
tests/query_error_test.rs

[query] Add QueryError #44

---

src/transaction.rs
tests/transaction_test.rs

[query] Add commit() to transaction #43

---

src/db.rs
src/transaction.rs
tests/db_test.rs
tests/transaction_test.rs

[query] Return Result<> from exec #47

---

src/transaction.rs
tests/transaction_test.rs

[query] Add rollback() to Transaction #49

---

src/lib.rs
src/storage.rs
src/storage/file_storage.rs

[storage] Add FileStorage #51

---

src/lib.rs
src/test_utilities.rs
src/test_utilities/test_file.rs

[tests] Add TestFile that auto-deletes #54

---

src/test_utilities/test_file.rs

[tests] Add TestFile::file_name() #56

---

src/storage/file_storage.rs

[storage] Construct FileStorage with filename and create a file #53

---

src/storage.rs
src/storage/file_index.rs
src/storage/file_storage.rs

[storage] Add FileIndex #59

---

src/storage/file_index.rs

[storage] Add index to position mapping to FileIndex #61

---

src/storage/file_index.rs

[storage] Add removal of index from FileIndex #63

---

src/storage/file_index.rs

[storage] Add free index to FileIndex #65

---

src/storage/file_index.rs

[storage] Add insert to FileIndex #67

---

src/storage.rs
src/storage/file_record.rs

[storage] Add FileRecord #69

---

src/storage/file_record.rs
src/storage/file_records.rs

[storage] Add From to FileRecords #73

---

src/storage.rs
src/storage/serialize.rs

[storage] Add Serialize trait #76

---

src/storage/file_record.rs
src/storage/file_storage.rs
src/storage/serialize.rs

[storage] Add insert() to FileStorage #75

---

src/storage/file_record.rs
src/storage/file_storage.rs

[storage] Add value() to FileStorage #79

---

src/storage.rs
src/storage/file_storage.rs
src/storage/file_wrapper.rs

[storage] Add FileWrapper to handle errors #84

---

src/storage/file_wrapper.rs

[storage] Add read() to FileWrapper #86

---

src/storage/file_wrapper.rs

[storage] Add current_pos() to FileWrapper #88

---

src/storage/file_wrapper.rs

[storage] Add write() to FileWrapper #90

---

src/storage/file_wrapper.rs

[storage] Add seek to FileWrapper #92

---

src/storage/file_wrapper.rs

[storage] Track size in FileWrapper #95

---

src/storage/file_storage.rs

[storage] Use FileWrapper in FileStorage #94

---

src/storage/file_storage.rs

[storage] Restore FileRecords from existing file #83

---

src/db_error.rs
src/lib.rs

[db] Add error type #100

---

src/test_utilities.rs
src/test_utilities/bad_file.rs

[tests] Add BadFile #102

---

src/test_utilities/bad_file.rs

[tests] Add more read_exact and write_all to BadFile #104

---

src/test_utilities/bad_file.rs

[tests] Add list of return values to BadFile #106

---

src/db_error.rs

[db] Convert io error to DbError #108

---

.github/workflows/pr.yaml
src/storage/file_storage.rs

[storage] Add insert with offset to FileStorage #113

---

src/storage/file_storage.rs

[storage] Add value_size() to FileStorage #117

---

src/storage/file_records.rs
src/storage/file_storage.rs

[storage] Stop using 0 as valid index #120

---

.github/workflows/pr.yaml
src/storage/file_records.rs
src/storage/file_storage.rs

[storage] Add remove() to FileStorage #122

---

src/storage/file_records.rs
src/storage/file_storage.rs

[storage] Use negative index to mark removed records #127

---

src/storage/file_records.rs

[storage] Remove separate free list from FileRecords #130

---

.github/workflows/pr.yaml
src/storage.rs
src/storage/file_record.rs
src/storage/file_record_full.rs
src/storage/file_records.rs
src/storage/file_storage.rs

[storage] Remove index from FileRecord #132

---

src/storage/file_records.rs

[storage] Make FileRecords iterable by position #125

---

.github/workflows/pr.yaml
src/storage/file_storage.rs

[storage] Add shrink_to_fit() to FileStorage #124

---

.github/workflows/pr.yaml
src/storage.rs
src/storage/write_ahead_log.rs

[storage] Add write ahead log struct #119

---

src/storage.rs
src/storage/write_ahead_log_record.rs

[storage] Add write ahead log record #137

---

.github/workflows/pr.yaml
src/storage/write_ahead_log.rs

[storage] Add write ahead log insert() #139

---

.github/workflows/pr.yaml
src/storage/file_storage.rs
src/storage/write_ahead_log.rs
src/storage/write_ahead_log_record.rs

[storage] Add records() to WriteAheadLog #140

---

.github/workflows/pr.yaml
src/storage/write_ahead_log.rs

[storage] Add clear() to WriteAheadLog #143

---

.github/workflows/pr.yaml
src/storage/file_records.rs
src/storage/file_storage.rs

[storage] Improve coverage #146

---

src/test_utilities/test_file.rs

[tests] Track write ahead log file in TestFile #148

---

.github/workflows/pr.yaml
src/storage/file_storage.rs
src/storage/write_ahead_log.rs

[storage] Add transactions to FileStorage #145

---

.github/workflows/pr.yaml
src/storage.rs
src/storage/file_storage.rs
src/storage/storage_impl.rs
src/storage/storage_record.rs
src/storage/storage_record_with_index.rs
src/storage/storage_records.rs

[storage] Add Storage trait #151

---

src/storage.rs
src/storage/storage_vec.rs

[storage] Add StorageVec #153

---

.github/workflows/pr.yaml
src/storage.rs
src/storage/file_storage.rs
src/storage/storage_impl.rs

[storage] Fix values not invalidated after move #158

---

.github/workflows/pr.yaml
src/storage/file_storage.rs
src/storage/storage_impl.rs

[storage] Fix move to end not resizing storage #160

---

.github/workflows/pr.yaml
src/storage/storage_vec.rs

[storage] Add push() to StorageVec #155

---

.github/workflows/pr.yaml
src/storage.rs
src/storage/file_storage.rs
src/storage/storage_impl.rs

[storage] Do not move values at end #163

---

src/storage/storage_vec.rs

[storage] Add mutable indexed access to StorageVec #167

---

src/storage/storage_vec.rs

[storage] Make StorageVec iterable #169

---

src/storage/storage_vec.rs

[storage] Rename index to file_index in StorageVec #171

---

src/storage/storage_vec.rs

[storage] Rename file_index to storage_index in StorageVec #173

---

src/storage/storage_vec.rs

[storage] Add conversion to Vec to StorageVec #175

---

.github/workflows/pr.yaml
src/storage.rs
src/storage/file_storage.rs
src/storage/storage_impl.rs

[storage] Add move_at to Storage #177

---

.github/workflows/pr.yaml
src/db_error.rs
src/lib.rs
src/storage.rs
src/storage/file_storage.rs
src/storage/serialize.rs
src/storage/storage_impl.rs
src/storage/storage_vec.rs

[db] Implement Error for DbError #179

---

.github/workflows/pr.yaml
src/storage/storage_vec.rs

[storage] Add remove() to StorageVec #181

---

.github/workflows/pr.yaml
src/storage/storage_vec.rs

[storage] Add resize() to StorageVec #183

---

src/storage/storage_vec.rs

[storage] Add reserve() to StorageVec #187

---

src/storage/storage_vec.rs

[storage] Add shrink_to_fit() to StorageVec #188

---

.github/workflows/pr.yaml
src/storage.rs
src/storage/storage_hash_map.rs

[storage] Add StorageHashMap #191

---

.github/workflows/pr.yaml
src/storage/storage_vec.rs

[storage] Add try_from storage and index to StorageVec #193

---

src/storage.rs
src/storage/stable_hash.rs

[storage] Add StableHash trait #196

---

.github/workflows/pr.yaml
src/storage.rs
src/storage/storage_hash_map_key_value.rs

[storage] Add StorageHashMapKeyValue struct #198

---

src/storage.rs
src/storage/storage_hash_map_key_value.rs
src/storage/storage_hash_map_meta_value.rs

[storage] Add empty indicator to StorageHashMapKeyValue #200

---

src/storage/storage_hash_map_key_value.rs
src/storage/storage_hash_map_meta_value.rs

[storage] Add serialized_size() to StorageHashMapKeyValue #203

---

.github/workflows/pr.yaml
src/storage.rs
src/storage/storage_hash_map_data.rs
src/storage/storage_hash_map_key_value.rs

[storage] Add StorageHashMapData struct #202

---

.github/workflows/pr.yaml
src/storage/file_storage.rs
src/storage/serialize.rs
src/storage/storage_hash_map_data.rs
src/storage/storage_hash_map_key_value.rs
src/storage/storage_hash_map_meta_value.rs
src/storage/storage_impl.rs
src/storage/storage_vec.rs

[storage] Add serialized_size to Serialize trait #206

---

.github/workflows/pr.yaml
src/storage/file_storage.rs
src/storage/storage_hash_map.rs
src/storage/storage_hash_map_data.rs
src/storage/storage_hash_map_key_value.rs
src/storage/storage_hash_map_meta_value.rs
src/storage/storage_impl.rs
src/storage/storage_vec.rs
src/storage/write_ahead_log.rs

[storage] Add insert and value to StorageHashMap #195

---

.github/workflows/pr.yaml
src/storage/storage_hash_map.rs

[storage] Add remove() to StorageHashMap #209

---

.github/workflows/pr.yaml
src/storage/storage_hash_map.rs

[storage] Insert duplicates should overwrite values in StorageHashMap #211

---

src/storage/storage_hash_map.rs

[storage] Add reserve() to StorageHashMap #213

---

.github/workflows/pr.yaml
src/storage/storage_hash_map.rs

[storage] Fix size of StorageHashMap incorrectly updates #215

---

.github/workflows/pr.yaml
src/storage/storage_hash_map.rs

[storage] Add to_hash_map() to StorageHashMap #218

---

.github/workflows/pr.yaml
src/storage/storage_hash_map.rs
src/storage/storage_vec.rs

[storage] Add try_from storage and index to StorageHashMap #217

---

src/db_error.rs

[db] Add conversion from FromUtf8Error to DbError #223

---

src/storage/file_storage.rs
src/storage/serialize.rs
src/storage/storage_hash_map.rs
src/storage/storage_hash_map_data.rs
src/storage/storage_hash_map_key_value.rs
src/storage/storage_impl.rs
src/storage/storage_record.rs
src/storage/storage_record_with_index.rs
src/storage/storage_records.rs
src/storage/storage_vec.rs
src/storage/write_ahead_log.rs

[storage] Add serialization for String #222

---

src/storage/file_storage.rs
src/storage/storage_hash_map.rs
src/storage/storage_vec.rs
src/storage/write_ahead_log.rs
src/test_utilities/test_file.rs

[tests] Use autogenerated name in TestFile #221

---

src/graph.rs
src/lib.rs

[graph] Add Graph struct #227

---

src/graph.rs
src/graph/graph_element.rs

[graph] Add GraphElement struct #229

---

src/graph.rs
src/graph/graph_node.rs

[graph] Add GraphNode struct #231

---

src/graph.rs
src/graph/graph_edge.rs

[graph] Add GraphEdge struct #233

---

src/graph.rs

[graph] Add insert_node() to Graph #235

---

src/graph.rs

[graph] Add node from index #243

---

.github/workflows/pr.yaml
src/graph.rs
src/graph/graph_edge.rs
src/graph/graph_edge_iterator.rs
src/graph/graph_impl.rs
src/graph/graph_node.rs
src/graph/graph_node_iterator.rs

[graph] Add remove_edge() to Graph #239

---

src/graph.rs

[graph] Add node_count() to Graph #251

---

.github/workflows/pr.yaml
src/graph.rs
src/graph/graph_data.rs
src/graph/graph_data_memory.rs
src/graph/graph_data_storage.rs
src/graph/graph_data_storage_indexes.rs
src/graph/graph_edge.rs
src/graph/graph_edge_iterator.rs
src/graph/graph_impl.rs
src/graph/graph_node.rs
src/graph/graph_node_iterator.rs
src/graph/storage_graph.rs
src/storage.rs
src/storage/storage_hash_map.rs
src/storage/storage_vec.rs

[graph] Add StorageGraph #257

---

.github/workflows/pr.yaml
src/storage/storage_hash_map.rs
src/storage/storage_vec.rs

[storage] Use transactions in Storage containers #260

---

.github/workflows/pr.yaml

[ci] Remove region coverage check #262

---

src/graph/graph_data.rs
src/graph/graph_data_memory.rs
src/graph/graph_data_storage.rs
src/graph/graph_impl.rs
src/graph/storage_graph.rs

[graph] Add transactions to Graph implementation #259

---

.github/workflows/pr.yaml
src/storage.rs
src/storage/hash_map_data.rs
src/storage/hash_map_data_memory.rs
src/storage/hash_map_data_storage.rs
src/storage/hash_map_impl.rs
src/storage/hash_multi_map.rs
src/storage/storage_hash_map.rs
src/storage/storage_hash_multi_map.rs

[storage] Add StorageHashMultiMap #266

---

src/storage.rs
src/storage/storage_vec.rs
src/storage/vec_iterator.rs

[storage] Add StorageVectorIterator #269

---

src/graph.rs
src/graph/dictionary.rs
src/graph/dictionary_data_storage.rs
src/graph/dictionary_data_storage_indexes.rs
src/graph/dictionary_impl.rs
src/graph/storage_dictionary.rs
src/storage/storage_vec.rs

[graph] Add StorageDictionary #275

---

.github/workflows/coverage.yaml

[ci] Fix codecov coverage not respecting workspace #279

---

crates/storage/src/lib.rs
crates/storage/src/storage_data_file.rs
crates/storage/src/storage_file.rs
crates/storage/src/storage_file_try_from.rs
crates/storage/tests/storage_file_insert_test.rs
crates/storage/tests/storage_file_move_at_test.rs
crates/storage/tests/storage_file_remove_test.rs
crates/storage/tests/storage_file_resize_value_test.rs
crates/storage/tests/storage_file_shrink_to_fit_test.rs
crates/storage/tests/storage_file_test.rs
crates/storage/tests/storage_file_transaction_test.rs
crates/storage/tests/storage_file_value_test.rs
src/graph/dictionary_data_storage.rs
src/graph/graph_data_storage.rs
src/graph/storage_dictionary.rs
src/graph/storage_graph.rs
src/storage/storage_hash_map.rs
src/storage/storage_hash_multi_map.rs
src/storage/storage_vec.rs

[storage] Rename FileStorage to StorageFile #289

---

crates/storage/src/storage_impl.rs
crates/storage/src/storage_impl_storage.rs
crates/storage_index/Cargo.toml
crates/storage_index/src/lib.rs
crates/storage_index/src/storage_index_serialize.rs
crates/storage_index/tests/storage_index_test.rs
src/graph/dictionary_data_storage_indexes.rs
src/graph/graph_data_storage_indexes.rs

[storage] Add StorageIndex serialization #293

---

crates/serialize/src/i64.rs
crates/serialize/src/serialize.rs
crates/serialize/src/u64.rs
crates/serialize/src/vec.rs
crates/storage/src/storage_data.rs
crates/storage/src/storage_data_file.rs
crates/storage/src/storage_impl.rs
crates/storage/src/storage_impl_storage.rs
crates/storage_index/src/lib.rs
crates/storage_index/src/storage_index.rs
crates/storage_index/src/storage_record.rs
crates/storage_index/src/storage_record_serialize.rs
crates/storage_index/src/storage_records.rs
crates/storage_index/tests/storage_record_test.rs
crates/storage_index/tests/storage_records_test.rs
src/graph/dictionary_data_storage_indexes.rs
src/graph/graph_data_storage_indexes.rs
src/storage/hash_map_data_storage.rs
src/storage/hash_map_meta_value.rs
src/storage/storage_hash_map.rs

[storage] Add StorageRecord serialization #295

---

README.md

[ci] Remove obsolete badge from readme #306

---

crates/graph/src/graph_data.rs
crates/graph/src/graph_data_memory.rs
crates/graph/src/graph_data_storage.rs
crates/graph/src/graph_edge.rs
crates/graph/src/graph_edge_iterator.rs
crates/graph/src/graph_impl.rs
crates/graph/src/graph_index.rs
crates/graph/src/graph_index_from.rs
crates/graph/src/graph_node.rs
crates/graph/src/graph_node_iterator.rs
crates/graph/src/lib.rs
crates/graph/src/storage_graph.rs
crates/graph/src/storage_graph_try_from.rs
crates/graph/tests/graph_edge_test.rs
crates/graph/tests/graph_index_test.rs
crates/graph/tests/graph_insert_edge_test.rs
crates/graph/tests/graph_insert_node_test.rs
crates/graph/tests/graph_node_test.rs
crates/graph/tests/graph_remove_edge_test.rs
crates/graph/tests/graph_remove_node_test.rs
crates/graph/tests/storage_graph_edge_test.rs
crates/graph/tests/storage_graph_insert_edge_test.rs
crates/graph/tests/storage_graph_insert_node_test.rs
crates/graph/tests/storage_graph_node_test.rs
crates/graph/tests/storage_graph_remove_edge_test.rs
crates/graph/tests/storage_graph_remove_node_test.rs
crates/graph/tests/storage_graph_test.rs

[graph] Add GraphIndex #309

---

crates/graph_search/Cargo.toml
crates/graph_search/src/lib.rs

[graph] Add GraphSearch crate #310

---

crates/graph_search/src/lib.rs
crates/graph_search/src/search_control.rs

[graph] Add SearchControl to GraphSearch #313

---

crates/graph_search/Cargo.toml
crates/graph_search/src/lib.rs
crates/graph_search/src/search_data.rs

[graph] Add SearchData to GraphSearch #316

---

crates/graph_search/src/lib.rs
crates/graph_search/src/search_handler.rs

[graph] Add SearchHandler trait to GraphSearch #315

---

crates/bit_set/Cargo.toml
crates/bit_set/src/bit_set.rs
crates/bit_set/src/lib.rs
crates/bit_set/tests/bit_set_test.rs

[storage] Add BitSet #319

---

crates/bit_set/src/bit_set.rs
crates/bit_set/tests/bit_set_test.rs
crates/graph/src/graph_edge.rs
crates/graph/src/graph_impl.rs
crates/graph/src/lib.rs
crates/graph/tests/graph_edge_test.rs
crates/graph_search/Cargo.toml
crates/graph_search/src/graph_search.rs
crates/graph_search/src/graph_search_from.rs
crates/graph_search/src/graph_search_index.rs
crates/graph_search/src/lib.rs
crates/graph_search/src/search_control.rs
crates/graph_search/src/search_data.rs
crates/graph_search/src/search_handler.rs
crates/graph_search/tests/breadth_first_search_test.rs

[graph] Add BreadthFirstSearch to GraphSearch #321

---

crates/graph_search/src/graph_search.rs
crates/graph_search/src/lib.rs
crates/graph_search/src/path.rs
crates/graph_search/src/path_search_handler.rs
crates/graph_search/src/path_search_impl.rs
crates/graph_search/src/search_impl.rs
crates/graph_search/tests/path_search_test.rs

[graph] Add PathSearch to GraphSearch #324

---

crates/graph/src/graph_edge.rs
crates/graph/src/graph_edge_reverse_iterator.rs
crates/graph/src/graph_impl.rs
crates/graph/src/graph_node.rs
crates/graph/src/lib.rs
crates/graph/tests/graph_edge_test.rs
crates/graph/tests/storage_graph_edge_test.rs
crates/graph_search/src/breadth_first_search_reverse.rs
crates/graph_search/src/depth_first_search_reverse.rs
crates/graph_search/src/graph_search.rs
crates/graph_search/src/lib.rs
crates/graph_search/src/path_search_impl.rs
crates/graph_search/src/search_impl.rs
crates/graph_search/src/search_iterator.rs
crates/graph_search/tests/breadth_first_search_test.rs
crates/graph_search/tests/depth_first_search_test.rs

[graph] Add reverse search to GraphSearch #326

---

crates/commands/Cargo.toml
crates/commands/src/commands.rs
crates/commands/src/lib.rs
crates/commands/tests/commands_test.rs
crates/db_error/src/db_error.rs

[commands] Add Commands enum #329

---

.github/workflows/build.yaml

[ci] Add publish dry run #335

---

README.md

[ci] Add readme build badge #337

---

src/agdb/db.rs
src/agdb/db/db_key.rs
src/agdb/lib.rs
tests/db_test.rs

[db] Add DbKey #341

---

src/agdb/db.rs
src/agdb/db/db_float.rs
src/agdb/db/db_value.rs
src/agdb/test_utilities/test_file.rs

[db] Implement traits for DbValue #343

---

src/agdb/db/db_float.rs
src/agdb/db/db_value.rs
src/agdb/utilities/stable_hash.rs

[db] Implement StableHash for DbValue #345

---

src/agdb/db/db_float.rs
src/agdb/db/db_value.rs
src/agdb/utilities/serialize.rs

[db] Implement Serialization for DbValue #347

---

.github/workflows/pr.yaml
src/agdb/collections/dictionary/dictionary_data_storage.rs
src/agdb/collections/dictionary/dictionary_data_storage_indexes.rs
src/agdb/collections/dictionary/dictionary_value.rs
src/agdb/collections/map_common/map_data_storage.rs
src/agdb/collections/map_common/map_value.rs
src/agdb/collections/map_common/map_value_state.rs
src/agdb/collections/storage_vec.rs
src/agdb/db/db_float.rs
src/agdb/db/db_value.rs
src/agdb/graph/graph_data_storage_indexes.rs
src/agdb/storage/storage_file.rs
src/agdb/storage/storage_impl.rs
src/agdb/storage/storage_index.rs
src/agdb/storage/storage_record.rs
src/agdb/storage/write_ahead_log.rs
src/agdb/utilities/serialize.rs

[db] Support serialization of dynamically sized types in Vec #350

---

.github/workflows/pr.yaml
.github/workflows/pr_title.yaml
src/agdb/collections/dictionary/dictionary_data_storage.rs
src/agdb/collections/map_common/map_data_storage.rs
src/agdb/collections/storage_vec.rs
src/agdb/storage.rs
src/agdb/storage/storage_file.rs
src/agdb/storage/storage_impl.rs

[collections] Add support for dynamic values in StorageVec #352

---

src/agdb/utilities/serialize.rs

[db] Add small value optimization #349

---

src/agdb/collections/dictionary/dictionary_data_storage.rs
src/agdb/collections/map_common/map_data_storage.rs
src/agdb/collections/storage_dictionary.rs
src/agdb/collections/storage_map.rs
src/agdb/collections/storage_multi_map.rs
src/agdb/collections/storage_vec.rs
src/agdb/collections/vec/storage_vec_iterator.rs
src/agdb/graph/graph_data_storage.rs
src/agdb/graph/storage_graph.rs
src/agdb/storage.rs
src/agdb/storage/partial_storage.rs
src/agdb/storage/storage_file.rs
src/agdb/storage/storage_impl.rs

[storage] Add new storage traits #358

---

src/agdb/db.rs
src/agdb/db/db_index.rs
src/agdb/lib.rs
src/agdb/utilities/serialize.rs

[db] Add DbIndex #361

---

src/agdb/collections.rs
src/agdb/graph.rs
src/agdb/graph/graph_data_storage.rs
src/agdb/graph/graph_data_storage_indexes.rs
src/agdb/graph/graph_storage.rs

[graph] Use VecStorage in graph #369

---

src/agdb/storage.rs
src/agdb/storage/storage_value.rs

[storage] Add StorageValue trait #372

---

src/agdb/collections/vec_storage.rs
src/agdb/db/db_index.rs
src/agdb/graph/graph_data_storage_indexes.rs
src/agdb/storage/file_storage.rs
src/agdb/storage/storage_index.rs
src/agdb/storage/storage_value.rs
src/agdb/storage/write_ahead_log.rs
src/agdb/utilities.rs
src/agdb/utilities/serialize.rs
src/agdb/utilities/serialize_static.rs

[db] Split static_serialized_size() to new trait #376

---

src/agdb/collections.rs
src/agdb/collections/map_storage.rs
src/agdb/collections/map_storage/map_storage_index.rs
src/agdb/collections/map_storage/map_storage_iterator.rs
src/agdb/collections/map_storage/map_value_state.rs
src/agdb/collections/vec_storage/vec_storage_iterator.rs
src/agdb/storage/storage_value.rs

[collections] Use VecStorage in Map #371

---

src/agdb/db.rs
src/agdb/db/db_element.rs
src/agdb/db/db_key_value.rs
src/agdb/query.rs
src/agdb/query/insert_edges_query.rs
src/agdb/query/insert_nodes_query.rs
src/agdb/query/insert_values_query.rs
src/agdb/query/query_ids.rs
src/agdb/query/query_result.rs
src/agdb/query/query_values.rs

[query] Add insert query #387

---

src/agdb/query.rs
src/agdb/query/query_ids.rs
src/agdb/query/query_values.rs
src/agdb/query/search_query.rs
src/agdb/query/select_keys_query.rs

[query] Add select query #389

---

src/agdb/collections/dictionary/dictionary_data_storage.rs
src/agdb/query.rs
src/agdb/query/insert_aliases_query.rs
src/agdb/query/insert_edges_query.rs
src/agdb/query/insert_nodes_query.rs
src/agdb/query/insert_query.rs
src/agdb/query/query_id.rs
src/agdb/query/query_ids.rs
src/agdb/query/query_values.rs
src/agdb/query/select_query.rs
src/agdb/storage/file_storage.rs

[query] Add remove query #391

---

src/agdb/query.rs
src/agdb/query/condition.rs
src/agdb/query/search_query.rs

[query] Add search query #393

---

src/agdb/query.rs
src/agdb/query/comparison_operator.rs
src/agdb/query/condition.rs
src/agdb/query/direction.rs
src/agdb/query/distance_condition.rs
src/agdb/query/edge_count_condition.rs
src/agdb/query/key_value_condition.rs
src/agdb/query/logic_operator.rs
src/agdb/query/search_query.rs

[query] Add condition #395

---

src/agdb/query/query_id.rs
src/agdb/query/query_ids.rs
src/agdb/query_builder/insert_node.rs
src/agdb/query_builder/insert_node_alias.rs
src/agdb/query_builder/insert_nodes.rs
src/agdb/query_builder/insert_nodes_aliases.rs
tests/insert_node_test.rs
tests/insert_nodes_test.rs

[query] Add values_id to insert nodes #401

---

src/agdb/db.rs
src/agdb/lib.rs
src/agdb/query.rs
src/agdb/query/insert_nodes_query.rs
src/agdb/query/query_values.rs
src/agdb/query/search_query.rs
src/agdb/query_builder.rs
src/agdb/query_builder/insert_node.rs
src/agdb/query_builder/insert_node_alias.rs
src/agdb/query_builder/insert_node_values.rs
src/agdb/query_builder/insert_nodes.rs
src/agdb/query_builder/insert_nodes_aliases.rs
src/agdb/query_builder/insert_nodes_count.rs
src/agdb/query_builder/insert_nodes_values.rs
src/agdb/query_builder/select.rs
src/agdb/query_builder/select_from.rs
src/agdb/transaction.rs
tests/insert_nodes_test.rs
tests/select_test.rs

[query] Add values_query #403

---

src/agdb/query_builder.rs
src/agdb/query_builder/insert.rs
src/agdb/query_builder/insert_edge.rs
src/agdb/query_builder/insert_edge_from.rs
src/agdb/query_builder/insert_edge_from_to.rs
src/agdb/query_builder/insert_edge_values.rs
tests/insert_edge_test.rs

[query] Add insert edge #405

---

src/agdb/query.rs
src/agdb/query/insert_values_query.rs
src/agdb/query_builder.rs
src/agdb/query_builder/insert.rs
src/agdb/query_builder/insert_values.rs
src/agdb/query_builder/insert_values_into.rs
src/agdb/query_builder/insert_values_multi.rs
tests/insert_values_test.rs

[query] Add insert values #409

---

src/agdb/query/insert_aliases_query.rs
src/agdb/query_builder.rs
src/agdb/query_builder/insert.rs
src/agdb/query_builder/insert_alias.rs
src/agdb/query_builder/insert_alias_of.rs
src/agdb/query_builder/insert_aliases.rs
tests/insert_alias_test.rs

[query] Insert alias #411

---

src/agdb/db.rs
src/agdb/lib.rs
src/agdb/query.rs
src/agdb/query/insert_aliases_query.rs
src/agdb/query/insert_edges_query.rs
src/agdb/query/insert_nodes_query.rs
src/agdb/query/insert_values_query.rs
src/agdb/query/remove_aliases_query.rs
src/agdb/query/remove_query.rs
src/agdb/query/remove_values_query.rs
src/agdb/query/search_query.rs
src/agdb/query/select_aliases_query.rs
src/agdb/query/select_count_query.rs
src/agdb/query/select_key_count_query.rs
src/agdb/query/select_keys_query.rs
src/agdb/query_builder.rs
src/agdb/query_builder/remove.rs
src/agdb/query_builder/remove_alias.rs
src/agdb/query_builder/select.rs
tests/remove_alias_test.rs

[query] Remove alias #413

---

src/agdb/query/insert_aliases_query.rs
src/agdb/query_builder.rs
src/agdb/query_builder/insert.rs
src/agdb/query_builder/insert_alias.rs
src/agdb/query_builder/insert_alias_of.rs
src/agdb/query_builder/insert_aliases.rs
src/agdb/query_builder/insert_aliases_of.rs
src/agdb/query_builder/remove.rs
src/agdb/query_builder/remove_values.rs
src/agdb/query_builder/remove_values_from.rs
tests/remove_values_test.rs

[query] Add remove values #415

---

src/agdb/query_builder.rs
src/agdb/query_builder/remove.rs
src/agdb/query_builder/remove_ids.rs
tests/remove_ids_test.rs

[query] Add remove ids query #417

---

src/agdb/query/select_keys_query.rs
src/agdb/query_builder/select.rs
tests/select_count_test.rs

[query] Add select count #423

---

src/agdb/query_builder.rs
src/agdb/query_builder/select.rs
src/agdb/query_builder/select_keys.rs
src/agdb/query_builder/select_keys_from.rs
tests/select_keys.rs

[query] Add select keys #427

---

src/agdb/query.rs
src/agdb/query/remove_values_query.rs
src/agdb/query/select_values_query.rs
src/agdb/query_builder.rs
src/agdb/query_builder/remove.rs
src/agdb/query_builder/select.rs
src/agdb/query_builder/select_values.rs
src/agdb/query_builder/select_values_from.rs
tests/select_values_test.rs

[query] Add select values #429

---

src/agdb/lib.rs
src/agdb/query.rs
src/agdb/query/comparison.rs
src/agdb/query/comparison_operator.rs
src/agdb/query/condition.rs
src/agdb/query/distance_condition.rs
src/agdb/query/edge_count_condition.rs
src/agdb/query/key_value_condition.rs
src/agdb/query_builder.rs
src/agdb/query_builder/search_from.rs
src/agdb/query_builder/where_.rs
src/agdb/query_builder/where_key.rs
src/agdb/query_builder/where_logic_operator.rs
tests/search_where_and_test.rs
tests/search_where_distance.rs
tests/search_where_edge_count_test.rs
tests/search_where_edge_test.rs
tests/search_where_ids_test.rs
tests/search_where_key.rs
tests/search_where_node_test.rs
tests/search_where_not_beyond.rs
tests/search_where_not_key.rs
tests/search_where_or_test.rs
tests/search_where_value_test.rs
tests/search_where_where_test.rs

[query] Add conditions #433

---

src/agdb/collections.rs
src/agdb/collections/indexed_map.rs

[collections] Add indexed map #438

---

src/agdb/collections.rs
src/agdb/collections/indexed_map.rs
src/agdb/collections/indexed_map/indexed_map_impl.rs
src/agdb/collections/indexed_map_storage.rs

[collections] Add storage indexed map #440

---

.github/workflows/pr.yaml

[ci] Add formatting check #442

---

.github/workflows/pr.yaml
src/agdb/commands.rs
src/agdb/commands/insert_alias.rs
src/agdb/commands/insert_edge.rs
src/agdb/commands/insert_node.rs
src/agdb/commands/remove_alias.rs
src/agdb/commands/remove_edge.rs
src/agdb/commands/remove_node.rs
src/agdb/db.rs
src/agdb/db/db_context.rs
src/agdb/query.rs
src/agdb/query/comparison.rs
src/agdb/query/condition.rs
src/agdb/query/direction.rs
src/agdb/query/edge_count_condition.rs
src/agdb/query/insert_edges_query.rs
src/agdb/query/key_value_condition.rs
src/agdb/query/query_error.rs
src/agdb/query/query_id.rs
src/agdb/query/query_ids.rs
src/agdb/query/search_query.rs
src/agdb/query_builder/select_alias.rs
src/agdb/query_builder/select_aliases.rs
src/agdb/test_utilities.rs
src/agdb/test_utilities/catch_unwidn_silent.rs
tests/insert_edges_test.rs

[db] Add insert edge #444

---

.github/workflows/pr.yaml
src/agdb/commands/remove_edge.rs
src/agdb/commands/remove_node.rs
src/agdb/db.rs
src/agdb/query.rs
src/agdb/query/insert_edges_query.rs
src/agdb/query/query_id.rs
src/agdb/query/remove_query.rs
tests/insert_edges_test.rs
tests/remove_ids_test.rs

[db] Remove nodes and edges #447

---

src/agdb/commands_mut/insert_alias.rs
src/agdb/commands_mut/insert_alias_id.rs
tests/insert_aliases_test.rs
tests/insert_nodes_test.rs

[db] Disallow empty alias #452

---

src/agdb/commands_mut.rs
src/agdb/commands_mut/insert_alias_id_result.rs
src/agdb/commands_mut/insert_alias_result.rs
src/agdb/commands_mut/remove_alias_result.rs
src/agdb/commands_mut/remove_edge.rs
src/agdb/commands_mut/remove_index.rs
src/agdb/commands_mut/remove_index_id.rs
src/agdb/query/insert_aliases_query.rs
src/agdb/query/remove_aliases_query.rs
src/agdb/transaction_mut.rs
tests/insert_aliases_test.rs
tests/remove_aliases_test.rs
tests/remove_ids_test.rs

[db] Skip removal of ids and aliases that do not exist #453

---

src/agdb/commands.rs
src/agdb/commands/select_id.rs
src/agdb/commands_mut/insert_edge.rs
src/agdb/commands_mut/remove_edge.rs
src/agdb/commands_mut/remove_edge_index.rs
src/agdb/db.rs
src/agdb/query/insert_aliases_query.rs
src/agdb/query/insert_edges_query.rs
src/agdb/query/query_id.rs
src/agdb/query/query_ids.rs
src/agdb/query/remove_query.rs
src/agdb/query/search_query.rs
src/agdb/query/select_query.rs
src/agdb/query_builder/insert.rs
src/agdb/query_builder/insert_alias.rs
src/agdb/query_builder/insert_aliases.rs
src/agdb/query_builder/search.rs
src/agdb/transaction.rs
tests/insert_aliases_test.rs

[query] Simplify insert alias query usage #465

---

src/agdb/commands_mut.rs
src/agdb/commands_mut/insert_alias.rs
src/agdb/commands_mut/insert_edge.rs
src/agdb/commands_mut/insert_index.rs
src/agdb/commands_mut/insert_node.rs
src/agdb/commands_mut/remove_alias.rs
src/agdb/commands_mut/remove_edge.rs
src/agdb/commands_mut/remove_index.rs
src/agdb/commands_mut/remove_node.rs
src/agdb/db.rs
src/agdb/query/insert_aliases_query.rs
src/agdb/query/insert_edges_query.rs
src/agdb/query/insert_nodes_query.rs
src/agdb/query/remove_aliases_query.rs
src/agdb/query/remove_query.rs
src/agdb/query_builder/remove.rs
src/agdb/transaction_mut.rs
tests/remove_ids_test.rs

[db] Switch commands to redo/undo #485

---

src/agdb/commands_mut/insert_alias.rs
src/agdb/commands_mut/insert_edge.rs
src/agdb/commands_mut/insert_index.rs
src/agdb/commands_mut/insert_node.rs
src/agdb/commands_mut/remove_alias.rs
src/agdb/commands_mut/remove_edge.rs
src/agdb/commands_mut/remove_index.rs
src/agdb/commands_mut/remove_node.rs
src/agdb/query/insert_nodes_query.rs
src/agdb/transaction_mut.rs
tests/insert_nodes_test.rs

[db] Make insert node atomic #487

---

.vscode/tasks.json

[ci] Add vscode tasks #488

---

src/agdb/graph.rs
src/agdb/graph/graph_impl.rs

[graph] Reinserted node cannot be used #498

---

src/agdb/commands_mut/remove_node.rs
tests/remove_ids_test.rs

[db] Handle edge in remove node #497

---

src/agdb/db.rs
src/agdb/db/db_value_index.rs

[db] Add db value index #503

---

src/agdb/commands_mut/insert_edge.rs
src/agdb/commands_mut/insert_node.rs
src/agdb/commands_mut/remove_edge.rs
src/agdb/commands_mut/remove_node.rs
src/agdb/graph/graph_index.rs

[graph] Add GraphIndex new #505

---

src/agdb/db.rs
src/agdb/db/db_key_value_index.rs

[db] Add db key value index #507

---

.github/workflows/coverage.yaml

[ci] Use --codecov instead of --lcov #510

---

.github/workflows/coverage.yaml

[ci] Revert to lcov style coverage #514

---

src/agdb/commands/select_id.rs
src/agdb/commands_mut.rs
src/agdb/commands_mut/insert_value.rs
src/agdb/db.rs
src/agdb/db/db_value.rs
src/agdb/db/db_value_index.rs
src/agdb/query/insert_values_query.rs
src/agdb/query/select_query.rs
src/agdb/query_builder/insert_values.rs
src/agdb/transaction.rs
src/agdb/transaction_mut.rs
tests/framework/mod.rs
tests/insert_value_test.rs

[db] Implement insert values query #509

---

src/agdb/collections/dictionary/dictionary_data.rs
src/agdb/collections/dictionary/dictionary_data_memory.rs
src/agdb/collections/dictionary/dictionary_data_storage.rs
src/agdb/collections/dictionary/dictionary_impl.rs
src/agdb/collections/map/map_data.rs
src/agdb/collections/map/map_data_memory.rs
src/agdb/collections/map/map_data_storage.rs
src/agdb/collections/map/multi_map_impl.rs
src/agdb/collections/vec_storage.rs
src/agdb/graph/graph_data.rs
src/agdb/graph/graph_data_memory.rs
src/agdb/graph/graph_data_storage.rs
src/agdb/graph/graph_impl.rs
src/agdb/storage.rs
src/agdb/storage/file_storage.rs

[storage] Add transaction identity #517

---

src/agdb/query/query_error.rs

[db] Include caused by DbError to QuerryError #519

---

src/agdb/db.rs
src/agdb/query/insert_nodes_query.rs
src/agdb/query/insert_values_query.rs
tests/insert_node_test.rs

[db] Add insert node values #461

---

src/agdb/command.rs
src/agdb/db.rs
tests/remove_node_test.rs

[db] Remove node with values #526

---

src/agdb/query/insert_edges_query.rs
tests/insert_edge_test.rs
tests/insert_value_test.rs

[db] Insert edge values #528

---

src/agdb/db.rs
src/agdb/query/remove_values_query.rs
src/agdb/query_builder/remove.rs
src/agdb/query_builder/remove_values.rs
tests/remove_value_test.rs

[db] Implement remove values #532

---

src/agdb/collections/dictionary.rs
src/agdb/collections/dictionary/dictionary_impl.rs
src/agdb/collections/dictionary_storage.rs
src/agdb/collections/indexed_map.rs
src/agdb/collections/indexed_map/indexed_map_impl.rs
src/agdb/collections/indexed_map_storage.rs
src/agdb/collections/map/map_data_memory.rs
src/agdb/collections/map/map_data_storage.rs
src/agdb/collections/map/map_impl.rs
src/agdb/collections/map/multi_map_impl.rs
src/agdb/collections/map_storage.rs
src/agdb/collections/multi_map.rs
src/agdb/collections/multi_map_storage.rs
src/agdb/collections/vec_storage.rs
src/agdb/db.rs
src/agdb/db/db_id.rs
src/agdb/db/db_key_value_index.rs
src/agdb/db/db_value_index.rs
src/agdb/graph/graph_data_storage.rs
src/agdb/graph/graph_impl.rs
src/agdb/graph/graph_index.rs
src/agdb/graph/graph_node.rs
src/agdb/graph/graph_storage.rs
src/agdb/query/select_query.rs
src/agdb/storage/file_storage.rs
tests/db_test.rs

[db] Add persistent store #462

---

src/agdb/command.rs
src/agdb/db.rs
src/agdb/db/db_id.rs
src/agdb/graph.rs
src/agdb/graph_search.rs
src/agdb/graph_search/breadth_first_search.rs
src/agdb/graph_search/breadth_first_search_reverse.rs
src/agdb/graph_search/depth_first_search.rs
src/agdb/graph_search/depth_first_search_reverse.rs
src/agdb/graph_search/path_search.rs
src/agdb/graph_search/path_search_handler.rs
src/agdb/graph_search/search_impl.rs
src/agdb/graph_search/search_index.rs
src/agdb/graph_search/search_iterator.rs
tests/select_test.rs

[db] Use GraphIndex as DbId #543

---

src/agdb/collections/indexed_map.rs
src/agdb/collections/map.rs
src/agdb/collections/multi_map.rs
src/agdb/db/db_id.rs
src/agdb/db/db_value_index.rs
src/agdb/storage.rs

[collections] Review type constraints #551

---

src/agdb/db.rs
src/agdb/query/select_aliases_query.rs
src/agdb/query/select_all_aliases_query.rs
src/agdb/query/select_query.rs
tests/select_aliases_test.rs
tests/test_db/mod.rs

[query] Implement select all aliases #555

---

src/agdb/db.rs
src/agdb/query/select_keys_query.rs
tests/select_keys.rs

[query] Implement select keys #558

---

src/agdb/db.rs
src/agdb/db/db_element.rs
src/agdb/db/db_value.rs
src/agdb/query/insert_edges_query.rs
src/agdb/query/insert_nodes_query.rs
src/agdb/query/select_aliases_query.rs
src/agdb/query/select_all_aliases_query.rs
src/agdb/query/select_key_count_query.rs
src/agdb/query/select_keys_query.rs
src/agdb/query/select_query.rs
src/agdb/query/select_values_query.rs
tests/db_test.rs
tests/insert_edges_test.rs
tests/insert_nodes_test.rs
tests/insert_values_test.rs
tests/remove_nodes_test.rs
tests/remove_values_test.rs
tests/select_aliases_test.rs
tests/select_key_count_test.rs
tests/select_keys.rs
tests/select_values_test.rs
tests/test_db/mod.rs

[query] Implement select values #557

---

src/agdb/db.rs
src/agdb/graph_search.rs
src/agdb/graph_search/breadth_first_search.rs
src/agdb/graph_search/breadth_first_search_reverse.rs
src/agdb/graph_search/depth_first_search.rs
src/agdb/graph_search/depth_first_search_reverse.rs
src/agdb/graph_search/search_impl.rs
src/agdb/query/search_query.rs
tests/search_test.rs

[query] Implement search query #565

---

src/agdb/db.rs
src/agdb/db/db_search_handlers.rs
src/agdb/graph_search.rs
src/agdb/graph_search/breadth_first_search.rs
src/agdb/graph_search/breadth_first_search_reverse.rs
src/agdb/graph_search/depth_first_search.rs
src/agdb/graph_search/depth_first_search_reverse.rs
src/agdb/graph_search/path_search.rs
src/agdb/graph_search/search_impl.rs
src/agdb/query/search_query.rs
tests/search_test.rs

[query] Implement search limit #567

---

src/agdb/db.rs
src/agdb/db/db_search_handlers.rs
src/agdb/query/search_query.rs
tests/search_test.rs

[query] Implement offset #568

---

src/agdb/query/search_query.rs
src/agdb/query/select_aliases_query.rs
src/agdb/query/select_key_count_query.rs
src/agdb/query/select_keys_query.rs
src/agdb/query/select_query.rs
src/agdb/query/select_values_query.rs
tests/select_aliases_test.rs
tests/select_key_count_test.rs
tests/select_keys.rs
tests/select_test.rs
tests/select_values_test.rs

[query] Implement search variants of select queries #574

---

src/agdb/db.rs
src/agdb/query/insert_edges_query.rs
src/agdb/query/insert_values_query.rs
src/agdb/query/remove_query.rs
src/agdb/query/remove_values_query.rs
tests/insert_edges_test.rs
tests/insert_values_test.rs
tests/remove_edges_test.rs
tests/remove_nodes_test.rs
tests/remove_values_test.rs

[query] Add search to insert and remove queries #577

---

src/agdb/query/query_result.rs
tests/insert_edges_test.rs
tests/test_db/mod.rs

[db] Add ids() to QueryResult #575

---

src/agdb/db/db_key.rs
src/agdb/lib.rs
src/agdb/query/search_query.rs
src/agdb/query_builder/search.rs
tests/insert_edges_test.rs
tests/insert_values_test.rs
tests/remove_edges_test.rs
tests/remove_nodes_test.rs
tests/remove_values_test.rs
tests/search_test.rs
tests/search_where_test.rs
tests/select_aliases_test.rs
tests/select_key_count_test.rs
tests/select_keys.rs
tests/select_test.rs
tests/select_values_test.rs

[query] Implement search ordering #569

---

src/agdb/db.rs
tests/db_test.rs
tests/test_db/mod.rs

[db] Add optimize on db drop #571

---

src/agdb/graph.rs
src/agdb/graph_search.rs
src/agdb/query/query_condition.rs
src/agdb/query/query_ids.rs
src/agdb/query/search_query.rs
src/agdb/test_utilities/collision_value.rs

[graph] Add edge count to #585

---

src/agdb/collections/multi_map.rs

[collections] Add find to MultiMap #583

---

src/agdb/collections/bit_set.rs
src/agdb/collections/multi_map.rs
src/agdb/db.rs
src/agdb/db/db_search_handlers.rs
src/agdb/graph.rs
src/agdb/graph_search.rs
src/agdb/graph_search/path_search.rs
src/agdb/lib.rs
src/agdb/query/query_condition.rs
src/agdb/query/search_query.rs
src/agdb/query_builder/search.rs
src/agdb/query_builder/where_.rs
src/agdb/storage/file_storage.rs
tests/search_test.rs
tests/search_where_test.rs
tests/test_db/mod.rs

[query] Implement conditions #581

---

.github/workflows/release.yaml

[ci] Fix release workflow #592

---

.github/workflows/release.yaml

[ci] Fix checkout action version #594

---

.github/workflows/release.yaml

[ci] Fix git push tag action #598

---

.github/workflows/release.yaml

[ci] Add missing -m option to git tag #600

---

README.md

[ci] Update crates badge to link to crates.io #602

---

docs/queries.md
src/agdb/db.rs
src/agdb/graph_search.rs
src/agdb/lib.rs
src/agdb/query/insert_aliases_query.rs
src/agdb/query/query_ids.rs
src/agdb/query/search_query.rs
src/agdb/query_builder/search.rs
src/agdb/query_builder/where_.rs
tests/search_test.rs

[query] Add ability to choose search algorithm #608

---

README.md
src/agdb/query/query_ids.rs
tests/db_test.rs
tests/examples.rs
tests/insert_edges_test.rs
tests/search_test.rs
tests/search_where_test.rs

[query] Add conversion from QueryResult to QueryIds #609

---

README.md
tests/examples.rs

[docs] Add missing usings to quickstart example #618

---

.github/FUNDING.yml

[ci] Add sponsorship #616

---

README.md

[docs] Add roadmap #612

---

src/agdb/query/query_ids.rs
src/agdb/query/query_result.rs

[db] Return Vec<DbId> from QueryResult::ids() #624

---

src/agdb/db/db_search_handlers.rs
tests/search_where_test.rs

[db] Penalize paths for skipped elements #625

---

docs/guide.md
docs/queries.md
src/agdb/query/query_ids.rs
src/agdb/query_builder/insert.rs
src/agdb/query_builder/insert_edge.rs
src/agdb/query_builder/insert_values.rs
src/agdb/query_builder/remove.rs
src/agdb/query_builder/remove_values.rs
src/agdb/query_builder/select.rs
src/agdb/query_builder/select_aliases.rs
src/agdb/query_builder/select_key_count.rs
src/agdb/query_builder/select_keys.rs
src/agdb/query_builder/select_values.rs
tests/examples.rs
tests/insert_edges_test.rs
tests/insert_values_test.rs
tests/remove_edges_test.rs
tests/remove_nodes_test.rs
tests/remove_values_test.rs
tests/search_test.rs
tests/select_aliases_test.rs
tests/select_key_count_test.rs
tests/select_keys.rs
tests/select_test.rs
tests/select_values_test.rs

[query] Add conversion from SearchQuery to QueryIds #629

---

src/agdb/query.rs
src/agdb/query/insert_aliases_query.rs
src/agdb/query/insert_edges_query.rs
src/agdb/query/insert_nodes_query.rs
src/agdb/query/insert_values_query.rs
src/agdb/query/remove_aliases_query.rs
src/agdb/query/remove_query.rs
src/agdb/query/remove_values_query.rs
src/agdb/query/search_query.rs
src/agdb/query/select_aliases_query.rs
src/agdb/query/select_all_aliases_query.rs
src/agdb/query/select_key_count_query.rs
src/agdb/query/select_keys_query.rs
src/agdb/query/select_query.rs
src/agdb/query/select_values_query.rs
src/agdb/transaction.rs
src/agdb/transaction_mut.rs

[db] Return QueryResult from Query::process #628

---

src/agdb/db.rs
src/agdb/query/query_condition.rs
tests/search_where_test.rs

[db] Fix edge_count condition stopping the search incorrectly #636

---

Cargo.toml

[ci] Release 0.2.0 #635

---

README.md
tests/quickstart.rs

[docs] Fix minor issues in docs #639

---

Cargo.toml

[ci] Release 0.2.1 #641

---

README.md
docs/queries.md

This reverts commit 7297910df16ef807bd4891f1b659b07e07bff8f5.

[docs] Revert mermaid links #1065
